package main

// Generated by templeGen. DO NOT EDIT!
var myTemplates = map[string]string{
	"home.tpl": "e3tpZiAuVXNlcn19SGVsbG8sIHt7LlVzZXIuTG9naW59fS4gPGEgaHJlZj0iL2xvZ291dCI+bG9nIG91dDwvYT57e2Vsc2V9fQpOb3QgbG9nZ2VkIGluLiA8YSBocmVmPSIvbG9naW4iPkxvZyBpbi48L2E+Cgp7e2VuZH19",
}
